// Code generated by goctl. DO NOT EDIT.
package types

type CaptchaReq struct {
	Username string `form:"username"`
}

type CaptchaResp struct {
	Code string `json:"code"`
}

type LoginReq struct {
	Username string `json:"username"` // 用户登录名称
	Password string `json:"password"` // 密码
	Captcha  string `json:"captcha"`  // 图形验证码
}

type LoginResp struct {
	Id          int64  `json:"id,optional"`
	Username    string `json:"username,optional"`
	AccessToken string `json:"access_token,optional"`
}

type GenerateTokenResp struct {
	Domain      string `json:"domain,optional"`
	QiniuAddr   string `json:"qiniuaddr,optional"`
	UploadToken string `json:"uploadToken,optional"`
}

type QiniuFileListReq struct {
	Marker    string `json:"marker,optional"`
	Limit     int    `json:"limit,optional"`
	Prefix    string `json:"prefix,optional"`
	Delimiter string `json:"delimiter,optional"`
}

type QiniuFileListResp struct {
	Rows           []QiNiuFile `json:"rows"`
	CommonPrefixes []string    `json:"commonPrefixes"`
	NextMarker     string      `json:"nextMarker"`
	HasNext        bool        `json:"hasNext"`
}

type QiNiuFile struct {
	Key      string `json:"key"`
	Hash     string `json:"hash"`
	Fsize    int64  `json:"fsize"`
	PutTime  int64  `json:"putTime"`
	MimeType string `json:"mimeType"`
	Type     int    `json:"type"`
	EndUser  string `json:"endUser"`
}

type PositiveMeditationCategoryListReq struct {
	Paging
}

type PositiveMeditationCategoryPageListResp struct {
	Total int64                         `json:"total"`
	Rows  []*PositiveMeditationCategory `json:"rows"`
}

type PositiveMeditationCategory struct {
	Id    int64  `json:"id,optional"`
	Title string `json:"title"`
	Icon  string `json:"icon"`
	Sort  int64  `json:"sort,optional"`
}

type PositiveMeditationCategoryEditReq struct {
	PositiveMeditationCategory
}

type PositiveMeditationCategoryDelReq struct {
	Id int64 `json:"id"`
}

type Paging struct {
	Page     int64 `json:"page,optional"`
	PageSize int64 `json:"page_size,optional"`
}

type PositiveMeditationTagListReq struct {
	Paging
	CategoryId  int64 `json:"category_id,optional"`
	IsRecommend int64 `json:"is_recommend,optional"`
}

type PositiveMeditationTagPageListResp struct {
	Total int64                    `json:"total"`
	Rows  []*PositiveMeditationTag `json:"rows"`
}

type PositiveMeditationTag struct {
	Id            int64  `json:"id,optional"`
	Title         string `json:"title,optional"`
	PicUrl        string `json:"pic_url,optional"`
	Explain       string `json:"explain,optional"`
	Sort          int64  `json:"sort,optional"`
	IsRecommend   int64  `json:"is_recommend,optional"`
	Icon          string `json:"icon,optional"`
	CategoryId    int64  `json:"category_id,optional"`
	CategoryTitle string `json:"category_title,optional"`
}

type PositiveMeditationTagEditReq struct {
	PositiveMeditationTag
}

type PositiveMeditationTagDelReq struct {
	Id int64 `json:"id"`
}

type PositiveMeditationListReq struct {
	Paging
	TagId       int64 `json:"tag_id,optional"`
	IsRecommend int64 `json:"is_recommend,optional"`
}

type PositiveMeditationPageListResp struct {
	Total int64                 `json:"total"`
	Rows  []*PositiveMeditation `json:"rows"`
}

type PositiveMeditation struct {
	Id           int64                    `json:"id,optional"`
	Title        string                   `json:"title"`
	PicUrl       string                   `json:"pic_url"`
	ThumbnailUrl string                   `json:"thumbnail_url"`
	ToppicUrl    string                   `json:"toppic_url"`
	VideoUrl     string                   `json:"video_url"`
	PlayTimes    int64                    `json:"play_times,optional"`
	Duration     string                   `json:"duration,optional"`
	Explain      string                   `json:"explain,optional"`
	Sort         int64                    `json:"sort,optional"`
	IsRecommend  int64                    `json:"is_recommend,optional"`
	TagList      []*PositiveMeditationTag `json:"tag_list,optional"`
}

type PositiveMeditationEditReq struct {
	PositiveMeditation
}

type PositiveMeditationDelReq struct {
	Id int64 `json:"id"`
}
